import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { FaChevronDown } from 'react-icons/fa';


const faqData = [
    {
      question: 'What services do solar providers typically offer?',
      answer: 'Solar providers offer a range of services, including solar panel installation, maintenance, repair, energy audits, and system monitoring. Some also offer financing options like leasing, loans, or Power Purchase Agreements (PPA).'
    },
    {
      question: 'How long do solar panels last?',
      answer: 'Solar panels typically last 25 to 30 years or more. Many providers offer warranties that cover panel efficiency and product performance over this period.'
    },
    {
      question: 'Can I install solar panels myself?',
      answer: 'While its possible to install solar panels on your own, we recommend letting our professional technical team handle the installation. They have the expertise to ensure the system is installed safely and operates at peak efficiency.'
    },
    {
      question: 'How much do solar panels cost?',
      answer: 'The cost of a solar panel system varies depending on the size of the system and type of panels. On average, a residential system can range between $10,000 and $30,000 before incentives.'
    },
    {
      question: 'Are there any financial incentives for installing solar panels?',
      answer: 'Yes, many regions offer incentives like federal tax credits, state rebates, and other local incentives. The federal government, for example, offers a 30% tax credit through the Solar Investment Tax Credit (ITC).'
    },
    {
      question: 'How does net metering work?',
      answer: 'Net metering allows you to send excess electricity generated by your solar panels back to the grid in exchange for credits, which can be used to offset your energy costs when your system isn’t generating enough power.'
    },
    {
      question: 'Do solar panels work during cloudy days or at night?',
      answer: 'Solar panels generate electricity when sunlight is available, so their efficiency decreases on cloudy days and they don’t work at night. However, a solar battery can store energy for use during these times.'
    },
  ];
  

const FaqItem = ({ question, answer }) => {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <div className="border-b border-gray-700 py-4">
      <motion.button
        className="flex justify-between items-center w-full text-left text-white"
        onClick={() => setIsOpen(!isOpen)}
        whileHover={{ scale: 1.01 }}
        whileTap={{ scale: 0.99 }}
      >
        <span className="text-sm sm:text-base md:text-lg font-medium pr-4">{question}</span>
        <motion.span
          animate={{ rotate: isOpen ? 180 : 0 }}
          transition={{ duration: 0.3 }}
        >
          <FaChevronDown />
        </motion.span>
      </motion.button>
      <AnimatePresence initial={false}>
        {isOpen && (
          <motion.div
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: 'auto' }}
            exit={{ opacity: 0, height: 0 }}
            transition={{ duration: 0.3 }}
            className="mt-2 text-gray-300 overflow-hidden"
          >
            <p className="text-xs sm:text-sm md:text-base">{answer}</p>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
};

const Faq = () => {
  return (
    <motion.section
      id="faq"
      className="bg-gray-900 py-6 sm:py-8 md:py-12"
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
    >
      <div className="w-11/12 sm:w-10/12 md:max-w-3xl mx-auto">
        <motion.h2
          className="text-xl sm:text-2xl md:text-3xl font-bold text-center mb-4 sm:mb-6 md:mb-8 text-white"
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.2 }}
        >
          Frequently Asked Questions
        </motion.h2>
        <motion.div
          className="space-y-3 sm:space-y-4 md:space-y-6"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.5, delay: 0.4 }}
        >
          {faqData.map((item, index) => (
            <FaqItem key={index} question={item.question} answer={item.answer} />
          ))}
        </motion.div>
      </div>
    </motion.section>
  );
};

export default Faq;
